USE LIBRARYDBM;
ALTER TABLE BOOKS
ADD COLUMN GENRE VARCHAR (50);
ALTER TABLE MEMBERS 
MODIFY COLUMN EMAIL VARCHAR(150);
ALTER TABLE TRANSACTIONS
DROP COLUMN PUBLISHEDYEAR;

ALTER table BOOKS
ADD COLUMN PUBLISHEDYEAR4 YEAR;
alter TABLE MEMBERS
ADD constraint UNIQUE_EMAIL UNIQUE (EMAIL);
SHOW CREATE TABLE MEMBERS;

